# Generated by Django 5.0.1 on 2024-03-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0003_produto_cor_produto_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('cd', 'CD'), ('roupa', 'Roupa'), ('vinil', 'Vinil')], max_length=50, null=True),
        ),
    ]
