# Generated by Django 5.0.1 on 2024-03-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0004_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='rituals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
