# Generated by Django 5.0.1 on 2024-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0005_rituals'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendas',
            field=models.IntegerField(default=0),
        ),
    ]
