# Generated by Django 5.0.1 on 2024-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0006_produto_vendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='static/src/img/Tshirt-AOCD.jpg', null=True, upload_to='produtos_imagens/'),
        ),
    ]
