# Generated by Django 5.0.1 on 2024-03-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0007_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='produtos_imagens/Tshirt-AOCD.jpg', null=True, upload_to='produtos_imagens/'),
        ),
    ]
