# Generated by Django 5.0.1 on 2024-03-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0008_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('XXl', 'XXL')], max_length=50, null=True),
        ),
    ]
