# Generated by Django 5.0.1 on 2024-03-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0010_country_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('localizacao', models.CharField(max_length=200)),
                ('hiperligacao', models.URLField()),
                ('foto', models.ImageField(upload_to='eventos_fotos/')),
            ],
        ),
        migrations.DeleteModel(
            name='rituals',
        ),
    ]
