# Generated by Django 5.0.1 on 2024-03-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0011_evento_delete_rituals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.CharField(),
        ),
    ]
