# Generated by Django 5.0.1 on 2024-03-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0012_alter_evento_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='shipping',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
