# Generated by Django 5.0.1 on 2024-03-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0013_country_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='shipping',
            field=models.FloatField(default=6.5),
        ),
    ]
