# Generated by Django 5.0.1 on 2024-03-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0014_alter_country_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=50)),
                ('stock_por_tamanho', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tamanho',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='produtotamanho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='Void.produto'),
        ),
    ]
