# Generated by Django 5.0.1 on 2024-03-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0015_produtotamanho_delete_tamanho_remove_produto_tamanho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='stock',
            field=models.IntegerField(blank=True),
        ),
    ]
