# Generated by Django 5.0.1 on 2024-03-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0017_rename_produto_produtotamanho_produto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtotamanho',
            name='tamanho',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=50),
        ),
    ]
