# Generated by Django 5.0.1 on 2024-03-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0018_alter_produtotamanho_tamanho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtotamanho',
            old_name='produto_id',
            new_name='produto',
        ),
    ]
