# Generated by Django 5.0.1 on 2024-03-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Void', '0019_rename_produto_id_produtotamanho_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtotamanho',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
